from .merge import deep_copy, deep_merge_in_place, deep_merge, set_nested
from .models import (
    get_artefacts_path,
    get_files_path,
    get_packages_path,
    get_artefact_key,
    get_object_key,
    generate_task_payload,
    generate_package_details,
    generate_deployment_details_from_stack,
    generate_deployment_details,
)
from .common import (
    split_prn,
    split_branch,
    split_portfolio,
    get_prn,
    get_prn_alt,
    get_region,
    get_client,
    get_automation_scope,
    generate_branch_short_name,
    generate_bucket_name,
    get_api_lambda_name,
    get_api_lambda_arn,
    get_invoker_lambda_arn,
    get_execute_lambda_arn,
    get_start_runner_lambda_arn,
    get_deployspec_compiler_lambda_arn,
    get_component_compiler_lambda_arn,
    get_dynamodb_host,
    get_dynamodb_region,
    get_bucket_region,
    get_bucket_name,
    get_step_function_arn,
    get_artefact_bucket_name,
    get_artefact_bucket_region,
    get_environment,
    is_local_mode,
    to_json,
    from_json,
)

from ._version import __version__

# import everything from prn_utils
from .prn_utils import (
    get_prn_scope,
    validate_item_prn,
    validate_portfolio_prn,
    validate_app_prn,
    validate_branch_prn,
    validate_build_prn,
    validate_component_prn,
    generate_portfolio_prn,
    generate_app_prn,
    generate_branch_prn,
    generate_build_prn,
    generate_component_prn,
    branch_short_name,
    extract_app,
    extract_portfolio,
    extract_branch,
    extract_build,
    extract_component,
    extract_portfolio_prn,
    extract_app_prn,
    extract_branch_prn,
    extract_build_prn,
    extract_component_prn,
)

__all__ = [
    "deep_copy",
    "deep_merge_in_place",
    "deep_merge",
    "set_nested",
    "get_artefacts_path",
    "get_files_path",
    "get_packages_path",
    "get_artefact_key",
    "get_object_key",
    "generate_task_payload",
    "generate_package_details",
    "generate_deployment_details_from_stack",
    "generate_deployment_details",
    "split_prn",
    "split_branch",
    "split_portfolio",
    "get_prn",
    "get_prn_alt",
    "get_region",
    "get_client",
    "get_automation_scope",
    "generate_branch_short_name",
    "generate_bucket_name",
    "get_api_lambda_name",
    "get_api_lambda_arn",
    "get_invoker_lambda_arn",
    "get_execute_lambda_arn",
    "get_start_runner_lambda_arn",
    "get_deployspec_compiler_lambda_arn",
    "get_component_compiler_lambda_arn",
    "get_dynamodb_host",
    "get_dynamodb_region",
    "get_bucket_region",
    "get_bucket_name",
    "get_step_function_arn",
    "get_artefact_bucket_name",
    "get_artefact_bucket_region",
    "get_environment",
    "is_local_mode",
    "to_json",
    "from_json",
    "get_prn_scope",
    "validate_item_prn",
    "validate_portfolio_prn",
    "validate_app_prn",
    "validate_branch_prn",
    "validate_build_prn",
    "validate_component_prn",
    "generate_portfolio_prn",
    "generate_app_prn",
    "generate_branch_prn",
    "generate_build_prn",
    "generate_component_prn",
    "branch_short_name",
    "extract_app",
    "extract_portfolio",
    "extract_branch",
    "extract_build",
    "extract_component",
    "extract_portfolio_prn",
    "extract_app_prn",
    "extract_branch_prn",
    "extract_build_prn",
    "extract_component_prn",
    "get_version",
]


def get_version():
    return __version__
